num1 = input("Enter Your First Number : ")
num2 = input("Enter Your Second Number : ")
sum = float(num1) + float(num2)
sub = float(num1) - float(num2)
print("The summation is : " ,sum)
print("The subtraction is : " ,sub)